transform:
  transform_resize: 25
  transform_resize_match: False
  #https://pytorch.org/docs/stable/torchvision/transforms.html
  #transform_resize_match: True
  transform_normalize: False
  transform_random_horizontal_flip: False
  transform_random_perspective: True
  transform_perspective_scale: 0.5
  transform_random_affine: False
  transform_degrees_min: -10.0
  transform_degrees_max: 10.0
  transform_translate_a: 0.2
  transform_translate_b: 0.2
  transform_random_resized_crop: False
  transform_random_rotation: True
  transform_random_rotation: True
  transform_random_rotation_degrees: 10
  transform_random_shear: True
  transform_random_shear_x1: 2
  transform_random_shear_x2: 2
  transform_random_shear_y1: 0
  transform_random_shear_y2: 0
  #transform_scale_a: 2
  #transform_scale_b: 4
  #RandomAffine(degrees, translate=None, scale=None, shear=None, resample=False, fillcolor=0)
