transform:
  transform_resize: 256
  transform_random_rotation: True
  transform_random_rotation_degrees: 5
  transform_resize_match: False
  transform_normalize: False
  transform_random_horizontal_flip: False
  transform_random_perspective: False
  transform_random_affine: False
  transform_random_resized_crop: False
  transform_random_shear: False
  #resize_h: 25
