dataset:
  name: "NTU_ONE_SHOT_NORMPOS_SKIPSECOND_RGB_POS_VEL"
  #data_dir: "/ntu/representations/normPos_skipSecond_RGB_pos_vel/one_shot_val"
  data_dir: "/ntu/representations/normPos_skipSecond_RGB_pos_vel/one_shot"
